#!/bin/bash
set -x
## Get version information
. conf
## Make a clean start
rm -rf scratch
mkdir scratch
cd scratch
wget https://www.zytor.com/pub/syslinux/Testing/${SYSLINUX_FOLDER}/${SYSLINUX}.tar.xz
tar xf ${SYSLINUX}.tar.xz
sed -i "s/Loading %s... \", kernel_name/\\\nLoading %s... \", kernel_name/g" syslinux-6.04-pre1/com32/elflink/ldlinux/kernel.c
sed -i "s/Loading %s...\", initrd_name/Loading %s... \", initrd_name/g" syslinux-6.04-pre1/com32/elflink/ldlinux/kernel.c
sed -i "s/Loading %s... \", kernel_name/\\\nLoading %s... \", kernel_name/g" syslinux-6.04-pre1/com32/modules/linux.c
cd ${SYSLINUX}
#make spotless
#make bios
make efi64
#make efi32
